# --- !Ups

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

ALTER TABLE amulets ALTER COLUMN guid SET DEFAULT uuid_generate_v4();

ALTER TABLE uploads ALTER COLUMN guid SET DEFAULT uuid_generate_v4();

ALTER TABLE chinas ALTER COLUMN guid SET DEFAULT uuid_generate_v4();

ALTER TABLE dreams ALTER COLUMN guid SET DEFAULT uuid_generate_v4();

ALTER TABLE druids ALTER COLUMN guid SET DEFAULT uuid_generate_v4();

ALTER TABLE flowers ALTER COLUMN guid SET DEFAULT uuid_generate_v4();

ALTER TABLE japans ALTER COLUMN guid SET DEFAULT uuid_generate_v4();

ALTER TABLE names ALTER COLUMN guid SET DEFAULT uuid_generate_v4();

ALTER TABLE periods ALTER COLUMN guid SET DEFAULT uuid_generate_v4();

ALTER TABLE horoscopes ALTER COLUMN guid SET DEFAULT uuid_generate_v4();

ALTER TABLE updates ALTER COLUMN guid SET DEFAULT uuid_generate_v4();

ALTER TABLE updates ALTER COLUMN date SET DEFAULT now();

# --- !Downs

ALTER TABLE amulets ALTER COLUMN guid DROP DEFAULT;

ALTER TABLE uploads ALTER COLUMN guid DROP DEFAULT;

ALTER TABLE chinas ALTER COLUMN guid DROP DEFAULT;

ALTER TABLE dreams ALTER COLUMN guid DROP DEFAULT;

ALTER TABLE druids ALTER COLUMN guid DROP DEFAULT;

ALTER TABLE flowers ALTER COLUMN guid DROP DEFAULT;

ALTER TABLE japans ALTER COLUMN guid DROP DEFAULT;

ALTER TABLE names ALTER COLUMN guid DROP DEFAULT;

ALTER TABLE periods ALTER COLUMN guid DROP DEFAULT;

ALTER TABLE horoscopes ALTER COLUMN guid DROP DEFAULT;

ALTER TABLE updates ALTER COLUMN guid DROP DEFAULT;

ALTER TABLE updates ALTER COLUMN date DROP DEFAULT;

DROP EXTENSION IF EXISTS "uuid-ossp";